# Generated by Django 3.1 on 2020-08-27 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='date',
            new_name='publish_date',
        ),
        migrations.AddField(
            model_name='blog',
            name='removal_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
